name: build_system
version: 0.0.3+1
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: >
  A simple package to trigger a build.dart script every time a file is added,
  changed or removed in the working tree.
homepage: https://github.com/a14n/build_system.dart

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  watcher: ^0.9.0

dev_dependencies:
  test: ^0.12.0
