name: build_system
version: 0.0.2
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A simple package to simulate the old Dart Editor behaviour when it called build.dart
homepage: https://github.com/a14n/dart-build-system

environment:
    sdk: ">=1.8.0 <2.0.0"

dependencies:
  watcher: ^0.9.0

dev_dependencies:
  test: any
